/**
 * OpenLigaDB-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BlTableTeam
 */
export interface BlTableTeam {

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    teamInfoId?: number;

    /**
     * @type {string}
     * @memberof BlTableTeam
     */
    teamName?: string | null;

    /**
     * @type {string}
     * @memberof BlTableTeam
     */
    shortName?: string | null;

    /**
     * @type {string}
     * @memberof BlTableTeam
     */
    teamIconUrl?: string | null;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    points?: number;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    opponentGoals?: number;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    goals?: number;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    matches?: number;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    won?: number;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    lost?: number;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    draw?: number;

    /**
     * @type {number}
     * @memberof BlTableTeam
     */
    goalDiff?: number;
}
