/**
 * OpenLigaDB-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Goal
 */
export interface Goal {

    /**
     * @type {number}
     * @memberof Goal
     */
    goalID?: number;

    /**
     * @type {number}
     * @memberof Goal
     */
    scoreTeam1?: number | null;

    /**
     * @type {number}
     * @memberof Goal
     */
    scoreTeam2?: number | null;

    /**
     * @type {number}
     * @memberof Goal
     */
    matchMinute?: number | null;

    /**
     * @type {number}
     * @memberof Goal
     */
    goalGetterID?: number;

    /**
     * @type {string}
     * @memberof Goal
     */
    goalGetterName?: string | null;

    /**
     * @type {boolean}
     * @memberof Goal
     */
    isPenalty?: boolean | null;

    /**
     * @type {boolean}
     * @memberof Goal
     */
    isOwnGoal?: boolean | null;

    /**
     * @type {boolean}
     * @memberof Goal
     */
    isOvertime?: boolean | null;

    /**
     * @type {string}
     * @memberof Goal
     */
    comment?: string | null;
}
