/**
 * OpenLigaDB-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GoalGetter
 */
export interface GoalGetter {

    /**
     * @type {number}
     * @memberof GoalGetter
     */
    goalGetterId?: number;

    /**
     * @type {string}
     * @memberof GoalGetter
     */
    goalGetterName?: string | null;

    /**
     * @type {number}
     * @memberof GoalGetter
     */
    goalCount?: number;
}
