/* tslint:disable */
/* eslint-disable */
/**
 * OpenLigaDB-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Group
 */
export interface Group {

    /**
     * @type {string}
     * @memberof Group
     */
    groupName?: string | null;

    /**
     * @type {number}
     * @memberof Group
     */
    groupOrderID?: number;

    /**
     * @type {number}
     * @memberof Group
     */
    groupID?: number;
}
