/**
 * OpenLigaDB-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Location
 */
export interface Location {

    /**
     * @type {number}
     * @memberof Location
     */
    locationID?: number;

    /**
     * @type {string}
     * @memberof Location
     */
    locationCity?: string | null;

    /**
     * @type {string}
     * @memberof Location
     */
    locationStadium?: string | null;
}
