/**
 * OpenLigaDB-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Goal } from './goal';
import { Group } from './group';
import { Location } from './location';
import { MatchResult } from './match-result';
import { Team } from './team';
 /**
 * 
 *
 * @export
 * @interface Match
 */
export interface Match {

    /**
     * @type {number}
     * @memberof Match
     */
    matchID?: number;

    /**
     * @type {Date}
     * @memberof Match
     */
    matchDateTime?: Date | null;

    /**
     * @type {string}
     * @memberof Match
     */
    timeZoneID?: string | null;

    /**
     * @type {number}
     * @memberof Match
     */
    leagueId?: number;

    /**
     * @type {string}
     * @memberof Match
     */
    leagueName?: string | null;

    /**
     * @type {number}
     * @memberof Match
     */
    leagueSeason?: number;

    /**
     * @type {string}
     * @memberof Match
     */
    leagueShortcut?: string | null;

    /**
     * @type {Date}
     * @memberof Match
     */
    matchDateTimeUTC?: Date | null;

    /**
     * @type {Group}
     * @memberof Match
     */
    group?: Group;

    /**
     * @type {Team}
     * @memberof Match
     */
    team1?: Team;

    /**
     * @type {Team}
     * @memberof Match
     */
    team2?: Team;

    /**
     * @type {Date}
     * @memberof Match
     */
    lastUpdateDateTime?: Date | null;

    /**
     * @type {boolean}
     * @memberof Match
     */
    matchIsFinished?: boolean;

    /**
     * @type {Array<MatchResult>}
     * @memberof Match
     */
    matchResults?: Array<MatchResult> | null;

    /**
     * @type {Array<Goal>}
     * @memberof Match
     */
    goals?: Array<Goal> | null;

    /**
     * @type {Location}
     * @memberof Match
     */
    location?: Location;

    /**
     * @type {number}
     * @memberof Match
     */
    numberOfViewers?: number | null;
}
