/**
 * OpenLigaDB-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Team
 */
export interface Team {

    /**
     * @type {number}
     * @memberof Team
     */
    teamId?: number;

    /**
     * @type {string}
     * @memberof Team
     */
    teamName?: string | null;

    /**
     * @type {string}
     * @memberof Team
     */
    shortName?: string | null;

    /**
     * @type {string}
     * @memberof Team
     */
    teamIconUrl?: string | null;

    /**
     * @type {string}
     * @memberof Team
     */
    teamGroupName?: string | null;
}
